"""Initial Migration

Revision ID: 81428f25b136
Revises: ff991160394a
Create Date: 2021-08-18 19:55:09.310384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81428f25b136'
down_revision = 'ff991160394a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
